apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: runtrade
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: gcr.io/erebe/runtrade
  local:
    useBuildkit: true
    # push: true
deploy:
  kubectl:
    defaultNamespace: "runtrade"
    manifests:
    - k8s/secrets_decrypted/*.yml
    - k8s/*.yml
