DROP TABLE IF EXISTS inscriptions CASCADE;
DROP TYPE IF EXISTS inscription_intent;
DROP TYPE IF EXISTS gender;
DROP TABLE IF EXISTS events;
DROP TYPE IF EXISTS event_type;
DROP TABLE IF EXISTS users;
DROP INDEX IF EXISTS idx_users_email_btree;
DROP INDEX IF EXISTS idx_users_externalid_btree;
DROP INDEX IF EXISTS idx_events_name_gin;
DROP INDEX IF EXISTS idx_events_localisation_gin;
DROP INDEX IF EXISTS idx_events_eventlink_gin;
